version: '3.1'
services:
  app:
    image: book_crossing
    container_name: book_crossing_app
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    ports:
      - 8088:8080
  php:
    container_name: php-fpm
    build:
      context: ./php
    ports:
      - 9000:9000
    depends_on:
      - db
    volumes:
      - ./app:/var/www/
      - ./php/php.ini:/usr/local/etc/php/php.ini
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - 8888:80
    volumes:
      - ./app:/var/www/
      - ./app/storage/app/public:/var/www/public/storage
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - php
      - db
  db:
    image: mysql:5.7
    container_name: book_crossing_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: book_crossing
      MYSQL_USER: pav5
      MYSQL_PASSWORD: admin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 6603:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
